version: "3.9"

services:
  app:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    tty: true
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./app:/usr/src/app
    command: >
      bash -c "
        python main.py &&
        /bin/bash
      "
